### PR TITLE
Add options to Stripe object

### PR DESCRIPTION
**Pull request by jorngeorg**
Here's a working example of how one could add options to the Stripe object such as locale and a custom font (https://stripe.com/docs/stripe.js#the-stripe-object), as I address in issue #6.

This would entail that we would need to add `elements` to `stripeOptions`.

### CODE REVIEW

**Comment by nkoehring** [comment]
@jorngeorg Thanks a lot for your contribution! I will merge your PR and some more changes and publish a new version in the next couple of hours!

**Comment by marcobarbosa** [comment]
Any examples on how to use this in the lib would be nice :) @jorngeorg  @nkoehring 

It's clear how to use `options` on one element:
```
<card-number
  :options='stripeOptios'
/>
```
These would be the `style`, `base` etc. But how to use the options to affect the `elements` instead?

**Comment by jorngeorg** [comment]
@marcobarbosa You would have to include an elements object to your options. So it would look something like this:

`const stripeOptions = {
  'hidePostalCode': true,
  'iconStyle': 'solid',
  // etc
'elements': {
    'locale': 'no',
    'fonts': [
      {
        'cssSrc': 'https://fonts.googleapis.com/css?family=Roboto+Mono'
      }
    ]
  },
}`

**Comment by marcobarbosa** [comment]
@jorngeorg Thank you very much!

**Comment by jwahdatehagh** [comment]
The problem is that the options object is passed to the `createToken()`, `createSource()` and `retrieveSource()` functions ([See here](https://github.com/fromAtoB/vue-stripe-elements/blob/master/src/stripeElements.js#L50)).

The createToken function should actually receive a `tokenData` object. ([See here](https://stripe.com/docs/stripe-js/reference?#stripe-create-token))
The createSource function gets a `sourceData` object ([See here](https://stripe.com/docs/stripe-js/reference?#stripe-create-source)).
And the retrieveSource function could actually get the Source object (returned from createSource) as its argument ([See here](https://stripe.com/docs/stripe-js/reference?#stripe-retrieve-source)):

> You can use a Source object created with stripe.createSource as the argument to stripe.retrieveSource, as every Source object has both id and client_secret keys.

If it would be sth you'd be interested in @nkoehring i'll try to find the time to submit a pr that splits the current options object into separate option configs.

**Pull request merged**
