### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lomholdt**
Added error handling example.

### CODE REVIEW

**Comment by lomholdt** [comment]
I just wanted to add the error handling example, since you then have a 1-to-1 working example as in  the Stripe documentation.

**Comment by softbeehive** [comment]
Hi @lomholdt, thanks for your example! I noticed that readme examples duplicate each other. I'm thinking about reducing their size. What do you think about following changes?

```html
# so we can have

<template>
   # ... example specific markup only
</template>
<script>
  # ... example specific JS
</script>
<style>
  # ... probably don't need styles
</style>
```

**Comment by lomholdt** [comment]
I think that's a great idea! 👍 🥇

**Comment by bkuhl** [comment]
@lomholdt 📟 ;)

**Pull request closed without merging**
